version: '3.7'

services:
  location:
    build: .

    environment:
      - VERTX_CONFIG_PATH=/opt/server/conf/config.json
    entrypoint: ["sh", "-c"]
    command: ["exec java -jar app.jar -cluster"]
    network_mode: "host"
